import Link from 'next/link';
import type { AccountIdentity, CustomerLoyalty, CustomerProfile } from '../lib/account';
import { SiteNavigation } from './site-navigation';

const money = (value: number) => 'Rp' + new Intl.NumberFormat('id-ID', { maximumFractionDigits: 0 }).format(value);
const points = (value: number) => new Intl.NumberFormat('id-ID', { maximumFractionDigits: 0 }).format(value) + ' poin';
const tierName = (code: string) => code === 'B2B_PREMIUM' ? 'Premium B2B' : 'Standard';

export function AccountOverview({ identity, profile, loyalty, needsProfile }: { identity: AccountIdentity; profile: CustomerProfile | null; loyalty: CustomerLoyalty | null; needsProfile: boolean }) {
  const paidOrders = profile?.paid_order_count ?? 0;
  const lifetimeSpend = profile?.lifetime_paid_amount_idr ?? 0;
  const tier = loyalty?.tier_code ?? 'STANDARD';
  const rate = (loyalty?.cashback_rate_bps ?? (tier === 'B2B_PREMIUM' ? 500 : 200)) / 100;

  return <><SiteNavigation identity={identity} profile={profile} needsProfile={needsProfile} /><main className="account-page"><div className="account-shell"><div className="account-heading"><div><p className="eyebrow">Luminails customer account</p><h1>Ruang order<br /><em>{identity.name}.</em></h1><p>Tier, histori pembelian, dan free product credit Anda ada di satu tempat.</p></div><div className="account-heading-actions"><Link className="button button-outline" href="/account/orders">Order history</Link><Link className="button button-outline" href="/account/addresses">Alamat cabang</Link><Link className="button button-outline" href="/account/profile">Edit profil</Link></div></div><section className="account-stat-grid"><div className="account-stat account-stat-coral"><span>Tier saat ini</span><strong>{tierName(tier)}</strong><small>Cashback {rate}% untuk order berikutnya</small></div><div className="account-stat account-stat-lilac"><span>Paid orders</span><strong>{paidOrders}</strong><small>Order berhasil dibayar</small></div><div className="account-stat account-stat-sage"><span>Lifetime spend</span><strong>{money(lifetimeSpend)}</strong><small>Total pembelian terbayar</small></div></section><section className="account-loyalty-card"><div><p className="eyebrow">Loyalty / Luminails Points</p><h2>{points(loyalty?.available_points ?? 0)}</h2><p>Poin non-uang yang dapat ditukar dengan free product saat purchase berikutnya.</p></div><div className="account-loyalty-rule"><span>Aturan Anda</span><strong>{tierName(tier)} · {rate}%</strong><small>Bukan uang, bukan potongan subtotal, dan tidak dapat diuangkan.</small></div></section>{needsProfile && <section className="account-profile-nudge"><div><p className="eyebrow">Lengkapi profil studio</p><h3>Supaya checkout berikutnya lebih cepat.</h3><p>Nama studio, nomor HP, dan alamat diperlukan untuk pengiriman package.</p></div><Link className="button button-dark" href="/account/profile">Lengkapi profil <span>→</span></Link></section>}<section className="account-how-it-works"><div><p className="eyebrow">How it works</p><h2>Belanja, kumpulkan,<br /><em>pilih produk gratis.</em></h2></div><div className="account-steps"><div><b>01</b><strong>Order dibayar</strong><span>Poin dihitung dari nilai order paid.</span></div><div><b>02</b><strong>Poin bertambah</strong><span>Standard 2%, Premium B2B 5%.</span></div><div><b>03</b><strong>Tukar poin ke produk gratis</strong><span>Pilih produk gratis pada purchase berikutnya.</span></div></div></section></div></main></>;
}
