import Link from 'next/link';
import type { CustomerOrder } from '../lib/orders-server';
import { buildRepeatOrderHref } from '../lib/orders-server';
import { cancelCheckoutOrder } from '../app/checkout/actions';

const money = (value: number) => 'Rp' + new Intl.NumberFormat('id-ID', { maximumFractionDigits: 0 }).format(value);
const statusName: Record<string, string> = { submitted_for_review: 'Menunggu review', awaiting_payment: 'Menunggu pembayaran', paid: 'Dibayar', fulfilling: 'Disiapkan', completed: 'Selesai', cancelled: 'Dibatalkan' };
const paymentName: Record<string, string> = { pending: 'Belum dibayar', paid: 'Dibayar', failed: 'Gagal', refunded: 'Refund', partially_refunded: 'Sebagian refund' };

export function CustomerOrderHistory({ orders, createdOrderId }: { orders: CustomerOrder[]; createdOrderId?: string }) {
  return <section className="order-history"><div className="account-panel order-history-intro"><p className="eyebrow">Luminails / order history</p><h2>Order yang tetap<br /><em>terlihat jelas.</em></h2><p>Status transaksi, promo yang terpakai, reservasi package, dan tracking akan muncul di sini.</p></div>{createdOrderId && <div className="order-success" role="status">Order <strong>{createdOrderId}</strong> sudah dibuat dan masuk ke back office untuk direview.</div>}{orders.length ? <div className="order-history-list">{orders.map((order) => { const repeatHref = buildRepeatOrderHref(order); return <article className="order-history-card" key={order.id}><div className="order-history-top"><div><span className="eyebrow">Order {order.id.slice(0, 8).toUpperCase()}</span><h3>{order.items.find((item) => item.item_type === 'package')?.product_name_snapshot ?? 'Luminails package order'}</h3><small>{new Date(order.created_at).toLocaleString('id-ID')}</small></div><strong>{money(order.total_idr)}</strong></div><div className="order-status-grid"><span>Status order<strong>{statusName[order.status] ?? order.status}</strong></span><span>Pembayaran<strong>{paymentName[order.payment_status] ?? order.payment_status}</strong></span><span>Fulfillment<strong>{order.shipment?.status ?? order.fulfillment_status}</strong></span></div><div className="order-item-lines">{order.items.filter((item) => item.item_type !== 'component').map((item) => <div key={item.id}><span>{item.product_name_snapshot} x {item.quantity}</span><strong>{item.item_type === 'loyalty_reward' ? 'Free product - points' : money(item.unit_price_idr * item.quantity)}</strong></div>)}</div><div className="order-history-foot"><span>{order.promotion_code ? 'Promo ' + order.promotion_code : 'Tanpa promo'} - {order.shipping_method === 'paxel_factory' ? 'Paxel next day gratis' : order.shipping_provider ?? order.shipping_method}</span><div className="order-history-links">{repeatHref && <Link className="underlined-link" href={repeatHref}>Beli lagi</Link>}{order.shipment?.tracking_url ? <a href={order.shipment.tracking_url} target="_blank" rel="noreferrer">Lihat tracking -&gt;</a> : <span>Tracking menyusul setelah fulfillment</span>}{['submitted_for_review', 'awaiting_payment'].includes(order.status) && <form action={cancelCheckoutOrder}><input type="hidden" name="order_id" value={order.id} /><button className="underlined-link" type="submit">Batalkan order</button></form>}</div></div></article>; })}</div> : <div className="account-panel order-empty"><h3>Belum ada order.</h3><p>Mulai dari package eksklusif untuk studio dan salon.</p><Link className="button button-dark" href="/packages">Browse packages <span>-&gt;</span></Link></div>}</section>;
}
