'use client';

import { useEffect, useMemo, useState, useActionState } from 'react';
import type { AdminDashboard } from '../lib/admin';
import { adjustCustomerPoints, archiveCustomerTier, archiveReward, deleteReward, saveCustomerOverride, saveCustomerTier, saveLoyaltySettings, saveReward, updateRedemptionStatus, type LoyaltyActionState } from '../app/admin/loyalty-actions';
import { recommendRewardPoints, rewardCostRatio } from '../lib/loyalty-engine';
import { LoyaltyRewardTable } from './loyalty-reward-table';

const money = (value: number) => 'Rp' + new Intl.NumberFormat('id-ID', { maximumFractionDigits: 0 }).format(value);
const points = (value: number) => new Intl.NumberFormat('id-ID').format(value);
const initial: LoyaltyActionState = { ok: false, message: '' };

export function LoyaltyAdminConsole({ dashboard, canPricing, canOrders }: { dashboard: AdminDashboard; canPricing: boolean; canOrders: boolean }) {
  const [section, setSection] = useState<'dashboard' | 'customers' | 'tiers' | 'rewards' | 'settings' | 'ledger' | 'redemptions' | 'activity'>('dashboard');
  return <div className="admin-crud-stack">
    <div className="admin-page-heading"><div><p className="eyebrow">Customer lifecycle / loyalty</p><h2>Customer & loyalty.</h2></div><span className="notification-count">{dashboard.customers.length} customer</span></div>
    <div className="admin-section-tabs" role="tablist">{[['dashboard', 'Dashboard'], ['customers', 'Customers'], ['tiers', 'Customer tiers'], ['rewards', 'Reward catalog'], ['redemptions', 'Redemptions'], ['settings', 'Loyalty settings'], ['ledger', 'Point ledger'], ['activity', 'Audit activity']].map(([value, label]) => <button key={value} type="button" className={section === value ? 'is-active' : ''} onClick={() => setSection(value as typeof section)}>{label}</button>)}</div>
    {section === 'dashboard' && <LoyaltyDashboard dashboard={dashboard} />}
    {section === 'customers' && <CustomersEnhanced dashboard={dashboard} canOrders={canOrders} canPricing={canPricing} />}
    {section === 'tiers' && <Tiers dashboard={dashboard} canEdit={canPricing} />}
    {section === 'rewards' && <RewardsEnhanced dashboard={dashboard} canEdit={canPricing} />}
    {section === 'redemptions' && <Redemptions dashboard={dashboard} canEdit={canOrders} />}
    {section === 'settings' && <Settings dashboard={dashboard} canEdit={canPricing} />}
    {section === 'ledger' && <Ledger dashboard={dashboard} />}
    {section === 'activity' && <Activity dashboard={dashboard} />}
  </div>;
}

function ActionMessage({ state }: { state: LoyaltyActionState }) { return state.message ? <p role="status" aria-live="polite" className={state.ok ? 'action-success' : 'action-error'}>{state.message}</p> : null; }

function RewardsEnhanced({ dashboard, canEdit }: { dashboard: AdminDashboard; canEdit: boolean }) {
  return <><RewardCreate dashboard={dashboard} canEdit={canEdit} /><LoyaltyRewardTable dashboard={dashboard} canEdit={canEdit} /></>;
}

function RewardCreate({ dashboard, canEdit }: { dashboard: AdminDashboard; canEdit: boolean }) {
  const [state, action, pending] = useActionState(saveReward, initial);
  const [hpp, setHpp] = useState('');
  const [pointCost, setPointCost] = useState('');
  const unit = Number(dashboard.loyaltySettings?.point_unit_value_idr ?? 10000);
  const warning = Number(dashboard.loyaltySettings?.reward_cost_warning_percent ?? 3);
  const maxMultiplier = Math.max(1, ...dashboard.customerTiers.filter((tier) => tier.is_active).map((tier) => Number(tier.point_multiplier) || 1));
  const recommended = recommendRewardPoints(Number(hpp) || 0, unit, warning, maxMultiplier);
  const pointValue = pointCost || (hpp ? String(recommended) : '');
  return <section className="admin-panel reward-create-panel"><div className="panel-heading"><div><p className="eyebrow">Free product catalog</p><h3>Tambah reward</h3></div><span className="notification-count">HPP / point ratio tervalidasi</span></div><p className="reward-pricing-explainer">Saran sistem memakai formula HPP × multiplier tier tertinggi ÷ nilai point agar estimasi cost reward berada di bawah {warning}% dari spend eligible. Anda tetap bisa menyesuaikan harga point sebelum menyimpan.</p><form className="admin-crud-form reward-create-form" action={action}>
    <label>SKU reward<select name="sku_id" required disabled={!canEdit}><option value="">Pilih SKU reward</option>{dashboard.skus.filter((sku) => sku.is_active).map((sku) => <option key={sku.id} value={sku.id}>{sku.sku} - {sku.name}</option>)}</select></label>
    <label>Nama reward<input name="reward_name" placeholder="Free Base Coat" disabled={!canEdit} required /></label>
    <label>Deskripsi<input name="description" placeholder="Produk gratis untuk tier" disabled={!canEdit} /></label>
    <label>HPP (IDR)<input name="hpp_idr" type="number" min={0} value={hpp} onChange={(event) => { setHpp(event.target.value.replace(/[^0-9]/g, '')); if (!pointCost) setPointCost(''); }} disabled={!canEdit} /><small className="field-help">Dipakai untuk menghitung saran point.</small></label>
    <label>Harga retail (IDR)<input name="normal_selling_price_idr" type="number" min={0} disabled={!canEdit} /></label>
    <label>Point cost<input name="points_cost" type="number" min={1} step={1} value={pointValue} onChange={(event) => setPointCost(event.target.value)} disabled={!canEdit} required /><small className="field-help">Saran sistem: {hpp ? `${recommended.toLocaleString('id-ID')} pts` : 'isi HPP terlebih dahulu'}.</small></label>
    <div className="reward-recommendation-box"><span>Saran point otomatis</span><strong>{hpp ? `${recommended.toLocaleString('id-ID')} pts` : '—'}</strong><button type="button" className="text-button" onClick={() => setPointCost(String(recommended))} disabled={!canEdit || !hpp}>Gunakan saran</button></div>
    <label>Minimum tier<select name="minimum_customer_tier_id" disabled={!canEdit}><option value="">Semua tier</option>{dashboard.customerTiers.map((tier) => <option key={tier.id} value={tier.id}>{tier.name}</option>)}</select></label><label>Minimum order<input name="minimum_order_value_idr" type="number" min={0} disabled={!canEdit} /></label><label>Max qty / redemption<input name="max_redemption_quantity" type="number" min={1} defaultValue={1} disabled={!canEdit} /></label><label>Stock (0 = unlimited)<input name="reward_stock" type="number" min={0} defaultValue={0} disabled={!canEdit} /></label>
    <label>Mulai (opsional)<input name="starts_at" type="datetime-local" disabled={!canEdit} /></label><label>Berakhir (opsional)<input name="ends_at" type="datetime-local" disabled={!canEdit} /></label><label className="admin-check"><input name="is_active" type="checkbox" defaultChecked disabled={!canEdit} /> Aktif</label><div className="admin-crud-action"><ActionMessage state={state} /><button className="button button-dark" disabled={!canEdit || pending}>{pending ? 'Menyimpan...' : 'Simpan reward'}</button></div>
  </form></section>;
}
function useDebounced(value: string) { const [debounced, setDebounced] = useState(value); useEffect(() => { const timer = window.setTimeout(() => setDebounced(value.trim().toLowerCase()), 300); return () => window.clearTimeout(timer); }, [value]); return debounced; }
function Pager({ page, total, onPage }: { page: number; total: number; onPage: (page: number) => void }) { const pages = Math.max(1, Math.ceil(total / 10)); return <div className="admin-pagination"><span>Halaman {Math.min(page + 1, pages)} / {pages} - {total} data</span><div><button type="button" className="button button-outline" disabled={page <= 0} onClick={() => onPage(Math.max(0, page - 1))}>Sebelumnya</button><button type="button" className="button button-outline" disabled={page >= pages - 1} onClick={() => onPage(Math.min(pages - 1, page + 1))}>Berikutnya</button></div></div>; }

function LoyaltyDashboard({ dashboard }: { dashboard: AdminDashboard }) {
  const activeCustomers = dashboard.customers.filter((customer) => !['suspended', 'rejected'].includes(customer.status));
  const monthStart = new Date();
  monthStart.setDate(1);
  monthStart.setHours(0, 0, 0, 0);
  const monthLedger = dashboard.pointTransactions.filter((row) => new Date(row.created_at) >= monthStart);
  const earned = monthLedger.filter((row) => row.entry_type === 'earn').reduce((sum, row) => sum + Math.max(0, row.points_delta), 0);
  const redeemed = monthLedger.filter((row) => row.entry_type === 'redeem').reduce((sum, row) => sum + Math.abs(row.points_delta), 0);
  const outstanding = dashboard.customers.reduce((sum, customer) => sum + customer.available_points, 0);
  const paidOrderCount = dashboard.orders.filter((order) => new Date(order.created_at) >= monthStart && ['paid', 'settled', 'completed'].includes(order.payment_status)).length;
  const redemptionOrderCount = new Set(dashboard.redemptions.filter((redemption) => redemption.created_at >= monthStart.toISOString()).map((redemption) => redemption.order_id).filter(Boolean)).size;
  const rewardCost = dashboard.redemptions.filter((redemption) => redemption.created_at >= monthStart.toISOString() && ['applied', 'confirmed', 'fulfilled'].includes(redemption.status)).reduce((sum, redemption) => sum + Number(dashboard.rewards.find((reward) => reward.sku_id === redemption.sku_id)?.hpp_idr ?? 0) * Math.max(1, Number(redemption.quantity ?? 1)), 0);
  const topSpend = [...dashboard.customers].sort((a, b) => b.lifetime_paid_amount_idr - a.lifetime_paid_amount_idr).slice(0, 5);
  const topPoints = [...dashboard.customers].sort((a, b) => b.available_points - a.available_points).slice(0, 5);
  const topRewards = [...dashboard.rewards].sort((a, b) => b.redemption_count - a.redemption_count).slice(0, 5);
  const expiring = [...dashboard.customers].filter((customer) => (customer.expiring_points ?? 0) > 0).sort((a, b) => new Date(a.next_expiry_at ?? '').getTime() - new Date(b.next_expiry_at ?? '').getTime()).slice(0, 5);
  const chartMax = Math.max(earned, redeemed, 1);
  const tierRows = dashboard.customerTiers.filter((tier) => tier.is_active).map((tier) => ({ key: tier.id, label: tier.name, value: `${dashboard.customers.filter((customer) => customer.customer_tier_id === tier.id).length} customer`, numericValue: dashboard.customers.filter((customer) => customer.customer_tier_id === tier.id).length })).sort((a, b) => b.numericValue - a.numericValue);
  const metrics = [
    { label: 'Customer aktif', value: points(activeCustomers.length), note: 'Akun yang bisa bertransaksi', tone: 'coral' },
    { label: 'Points beredar', value: points(outstanding) + ' pts', note: 'Saldo points seluruh customer', tone: 'lilac' },
    { label: 'Points didapat bulan ini', value: '+' + points(earned), note: 'Dari transaksi eligible', tone: 'sage' },
    { label: 'Points ditukar bulan ini', value: '-' + points(redeemed), note: 'Dari reward yang dipakai', tone: 'paper' },
    { label: 'Rasio penukaran', value: paidOrderCount ? String(Math.round((redemptionOrderCount / paidOrderCount) * 100)) + '%' : '0%', note: redemptionOrderCount + ' dari ' + paidOrderCount + ' order paid', tone: 'pink' },
    { label: 'Biaya reward bulan ini', value: money(rewardCost), note: 'Estimasi HPP reward terpenuhi', tone: 'ink' },
  ];
  return <section className="loyalty-dashboard">
    <header className="loyalty-dashboard-intro"><div><p className="eyebrow">Loyalty overview</p><h3>Customer yang kembali<br /><em>membuat bisnis lebih kuat.</em></h3></div><p>Gunakan ringkasan ini untuk melihat kesehatan customer, pergerakan points, dan peluang reward tanpa membaca angka mentah satu per satu.</p></header>
    <section className="loyalty-dashboard-metrics" aria-label="Ringkasan loyalty">{metrics.map((metric) => <article className={'loyalty-metric-card loyalty-metric-' + metric.tone} key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong><small>{metric.note}</small></article>)}</section>
    <section className="loyalty-dashboard-visuals">
      <section className="admin-panel loyalty-chart-panel"><div className="panel-heading"><div><p className="eyebrow">Pergerakan points</p><h3>Bulan ini</h3></div><span className="notification-count">{monthLedger.length} aktivitas</span></div><div className="loyalty-bar-chart" role="img" aria-label={'Points didapat ' + points(earned) + ', points ditukar ' + points(redeemed)}><div className="loyalty-chart-scale"><span>0</span><span>{points(chartMax)} pts</span></div><div className="loyalty-bar-row"><span>Didapat</span><div className="loyalty-bar-track"><i className="loyalty-bar-earned" style={{ width: String(Math.max(earned / chartMax * 100, earned ? 4 : 0)) + '%' }} /></div><strong>+{points(earned)}</strong></div><div className="loyalty-bar-row"><span>Ditukar</span><div className="loyalty-bar-track"><i className="loyalty-bar-redeemed" style={{ width: String(Math.max(redeemed / chartMax * 100, redeemed ? 4 : 0)) + '%' }} /></div><strong>-{points(redeemed)}</strong></div></div><p className="loyalty-chart-note">Grafik membandingkan points masuk dan points keluar pada periode kalender berjalan.</p></section>
      <section className="admin-panel loyalty-tier-chart"><div className="panel-heading"><div><p className="eyebrow">Komposisi customer</p><h3>Distribusi tier</h3></div><span className="notification-count">{activeCustomers.length} aktif</span></div>{tierRows.length ? <div className="loyalty-tier-bars">{tierRows.map((row) => <div className="loyalty-tier-bar-row" key={row.key}><div><span>{row.label}</span><strong>{row.value}</strong></div><div className="loyalty-bar-track"><i style={{ width: String(Math.max(row.numericValue / Math.max(activeCustomers.length, 1) * 100, row.numericValue ? 4 : 0)) + '%' }} /></div></div>)}</div> : <p className="admin-empty-copy">Tier belum tersedia.</p>}<p className="loyalty-chart-note">Distribusi membantu melihat apakah customer mulai naik dari Basic ke Premium atau VIP.</p></section>
    </section>
    <section className="loyalty-dashboard-rankings"><DashboardList title="Customer dengan belanja tertinggi" caption="Total belanja" rows={topSpend.map((customer) => ({ key: customer.id, label: customer.business_name || customer.display_name || customer.id, value: money(customer.lifetime_paid_amount_idr), numericValue: customer.lifetime_paid_amount_idr }))} /><DashboardList title="Customer dengan points terbanyak" caption="Saldo tersedia" rows={topPoints.map((customer) => ({ key: customer.id, label: customer.business_name || customer.display_name || customer.email || customer.id, value: points(customer.available_points) + ' pts', numericValue: customer.available_points }))} /><DashboardList title="Reward paling sering ditukar" caption="Jumlah redemption" rows={topRewards.map((reward) => ({ key: reward.id, label: reward.reward_name || reward.sku_name || reward.sku_id, value: points(reward.redemption_count) + 'x', numericValue: reward.redemption_count }))} /></section>
    <section className="admin-panel loyalty-expiry-panel"><div className="panel-heading"><div><p className="eyebrow">Expiry watch</p><h3>Points yang akan berakhir</h3></div><span className="notification-count">30 hari ke depan</span></div>{expiring.length ? <div className="loyalty-expiry-list">{expiring.map((customer) => <div className="loyalty-expiry-row" key={customer.id}><div><strong>{customer.business_name || customer.display_name || customer.email || customer.id}</strong><small>{customer.next_expiry_at ? new Date(customer.next_expiry_at).toLocaleDateString('id-ID') : 'Tanggal belum ditentukan'}</small></div><b>{points(customer.expiring_points ?? 0)} pts</b></div>)}</div> : <p className="admin-help-copy">Belum ada points yang akan berakhir dalam 30 hari.</p>}</section>
  </section>;
}

function DashboardList({ title, caption, rows }: { title: string; caption: string; rows: Array<{ key: string; label: string; value: string; numericValue: number }> }) {
  const maxValue = Math.max(...rows.map((row) => row.numericValue), 1);
  return <section className="admin-panel dashboard-ranking-panel"><div className="panel-heading"><div><h3>{title}</h3><span className="dashboard-ranking-caption">{caption}</span></div><span className="notification-count">Top {rows.length}</span></div>{rows.length ? <div className="dashboard-ranking-list">{rows.map((row) => <div className="dashboard-ranking-row" key={row.key}><div className="dashboard-ranking-meta"><span>{row.label}</span><strong>{row.value}</strong></div><div className="loyalty-bar-track"><i style={{ width: String(Math.max(row.numericValue / maxValue * 100, row.numericValue ? 4 : 0)) + '%' }} /></div></div>)}</div> : <p className="admin-empty-copy">Belum ada data untuk ditampilkan.</p>}</section>;
}
function Activity({ dashboard }: { dashboard: AdminDashboard }) {
  const [query, setQuery] = useState('');
  const debounced = useDebounced(query);
  const [entity, setEntity] = useState('all');
  const [action, setAction] = useState('all');
  const [sort, setSort] = useState('newest');
  const [page, setPage] = useState(0);
  const entities = useMemo(() => Array.from(new Set(dashboard.auditLogs.map((row) => row.entity_type))).sort(), [dashboard.auditLogs]);
  const actions = useMemo(() => Array.from(new Set(dashboard.auditLogs.map((row) => row.action))).sort(), [dashboard.auditLogs]);
  const rows = useMemo(() => dashboard.auditLogs.filter((row) => {
    const text = [row.action, row.entity_type, row.entity_id, row.actor_id, JSON.stringify(row.old_value), JSON.stringify(row.new_value)].filter(Boolean).join(' ').toLowerCase();
    return text.includes(debounced) && (entity === 'all' || row.entity_type === entity) && (action === 'all' || row.action === action);
  }).sort((a, b) => sort === 'oldest' ? a.created_at.localeCompare(b.created_at) : b.created_at.localeCompare(a.created_at)), [dashboard.auditLogs, debounced, entity, action, sort]);
  return <section className={'admin-panel'}><div className={'panel-heading'}><div><p className={'eyebrow'}>Admin audit trail</p><h3>Activity</h3></div><span className={'notification-count'}>{rows.length} of {dashboard.auditLogs.length} events</span></div>
    <div className="admin-table-controls"><label className="admin-table-search-label">Search<input className={'admin-table-search'} value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} placeholder={'Action, entity, actor, atau perubahan'} /></label><label>Entity<select value={entity} onChange={(event) => { setEntity(event.target.value); setPage(0); }}><option value="all">Semua entity</option>{entities.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label>Action<select value={action} onChange={(event) => { setAction(event.target.value); setPage(0); }}><option value="all">Semua action</option>{actions.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label>Urutkan<select value={sort} onChange={(event) => { setSort(event.target.value); setPage(0); }}><option value="newest">Terbaru</option><option value="oldest">Terlama</option></select></label></div>
    <div className="admin-data-table audit-table"><div className="admin-data-head"><span>Tanggal</span><span>Action</span><span>Entity</span><span>Actor</span><span>Perubahan lama</span><span>Perubahan baru</span></div>{rows.slice(page * 10, page * 10 + 10).map((row) => <div className="admin-data-row" key={row.id}><span>{new Date(row.created_at).toLocaleString('id-ID')}</span><span>{row.action}</span><span>{row.entity_type}<small>{row.entity_id || '-'}</small></span><span>{row.actor_id || 'System'}</span><span><code>{row.old_value ? JSON.stringify(row.old_value) : '-'}</code></span><span><code>{row.new_value ? JSON.stringify(row.new_value) : '-'}</code></span></div>)}</div>
    {!rows.length && <p className={'admin-empty-copy'}>Belum ada activity audit yang cocok.</p>}<Pager page={page} total={rows.length} onPage={setPage} /></section>;
}
function CustomersEnhanced({ dashboard, canOrders, canPricing }: { dashboard: AdminDashboard; canOrders: boolean; canPricing: boolean }) {
  const [query, setQuery] = useState('');
  const debounced = useDebounced(query);
  const [tier, setTier] = useState('all');
  const [status, setStatus] = useState('all');
  const [override, setOverride] = useState('all');
  const [pointMin, setPointMin] = useState('');
  const [pointMax, setPointMax] = useState('');
  const [sort, setSort] = useState('newest');
  const [page, setPage] = useState(0);
  const [selectedId, setSelectedId] = useState<string | null>(dashboard.customers[0]?.id ?? null);

  const inRange = (value: number, minimum: string, maximum: string) => (!minimum || value >= Number(minimum)) && (!maximum || value <= Number(maximum));
  const rows = useMemo(() => dashboard.customers.filter((customer) => {
    const text = [customer.display_name, customer.business_name, customer.email, customer.phone, customer.whatsapp, customer.id].filter(Boolean).join(' ').toLowerCase();
    return text.includes(debounced)
      && (tier === 'all' || customer.customer_tier_id === tier)
      && (status === 'all' || customer.status === status)
      && (override === 'all' || (override === 'yes' ? customer.manual_tier_override_enabled : !customer.manual_tier_override_enabled))
      && inRange(customer.available_points, pointMin, pointMax)
      && inRange(customer.available_points, pointMin, pointMax);
  }).sort((a, b) => {
    if (sort === 'name') return (a.business_name || a.display_name || '').localeCompare(b.business_name || b.display_name || '');
    if (sort === 'points') return b.available_points - a.available_points;
    if (sort === 'orders') return b.paid_order_count - a.paid_order_count;
    if (sort === 'last') return (b.last_order_at ?? '').localeCompare(a.last_order_at ?? '');
    if (sort === 'oldest') return a.created_at.localeCompare(b.created_at);
    return b.created_at.localeCompare(a.created_at);
  }), [dashboard.customers, debounced, tier, status, override, pointMin, pointMax, sort]);
  const selected = dashboard.customers.find((customer) => customer.id === selectedId) ?? null;
  const resetPage = () => setPage(0);
  return <><section className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">Customer management</p><h3>Customer table</h3></div><span className="notification-count">Search debounce 300ms</span></div>
    <div className="admin-table-controls customer-table-controls">
      <label className="admin-table-search-label">Search<input className="admin-table-search" type="search" value={query} onChange={(event) => { setQuery(event.target.value); resetPage(); }} placeholder="Nama, company, WhatsApp, email, atau ID" /></label>
      <label>Tier<select value={tier} onChange={(event) => { setTier(event.target.value); resetPage(); }}><option value="all">Semua tier</option>{dashboard.customerTiers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label>Status<select value={status} onChange={(event) => { setStatus(event.target.value); resetPage(); }}><option value="all">Semua status</option><option value="approved">Approved</option><option value="pending">Pending</option><option value="suspended">Suspended</option><option value="rejected">Rejected</option></select></label>
      <label>Override<select value={override} onChange={(event) => { setOverride(event.target.value); resetPage(); }}><option value="all">Override: semua</option><option value="yes">Override aktif</option><option value="no">Auto tier</option></select></label>
      <label>Points min<input inputMode="numeric" value={pointMin} onChange={(event) => { setPointMin(event.target.value); resetPage(); }} placeholder="0" /></label>
      <label>Points max<input inputMode="numeric" value={pointMax} onChange={(event) => { setPointMax(event.target.value); resetPage(); }} placeholder="Tidak dibatasi" /></label>
      <label>Sort<select value={sort} onChange={(event) => { setSort(event.target.value); resetPage(); }}><option value="newest">Terbaru</option><option value="oldest">Terlama</option><option value="name">Nama</option><option value="points">Points</option><option value="orders">Total orders</option><option value="last">Last order</option></select></label>
    </div>
    <div className="admin-data-table customer-table"><div className="admin-data-head"><span>Customer</span><span>Company</span><span>WhatsApp</span><span>Tier</span><span>Belanja periode</span><span>Total belanja</span><span>Points</span><span>Orders</span><span>Last order</span><span>Status</span><span>Actions</span></div>
      {rows.slice(page * 10, page * 10 + 10).map((customer) => <button type="button" className={`admin-data-row${customer.id === selectedId ? ' is-selected' : ''}`} key={customer.id} onClick={() => setSelectedId(customer.id)}>
        <span><strong>{customer.display_name || 'Tanpa nama'}</strong><small>{customer.email || customer.id}</small></span>
        <span>{customer.business_name || '-'}</span>
        <span>{customer.whatsapp || customer.phone || '-'}</span>
        <span><strong>{dashboard.customerTiers.find((item) => item.id === customer.customer_tier_id)?.name ?? 'Basic'}</strong>{customer.manual_tier_override_enabled ? <small>Override aktif</small> : null}</span>
        <span>{money(customer.rolling_spend_idr ?? 0)}</span>
        <span>{money(customer.lifetime_paid_amount_idr)}</span>
        <span>{points(customer.available_points)} pts{customer.expiring_points ? <small>{points(customer.expiring_points)} expiring</small> : null}</span>
        <span>{customer.paid_order_count}</span>
        <span>{customer.last_order_at ? new Date(customer.last_order_at).toLocaleDateString('id-ID') : '-'}</span>
        <span>{customer.status}</span>
        <span>Detail -&gt;</span>
      </button>)}
    </div>
    {!rows.length && <p className="admin-empty-copy">Tidak ada customer yang cocok dengan filter.</p>}
    <Pager page={page} total={rows.length} onPage={setPage} />
  </section>{selected && <CustomerDetail customer={selected} tier={dashboard.customerTiers.find((item) => item.id === selected.customer_tier_id)} dashboard={dashboard} canOrders={canOrders} canPricing={canPricing} />}</>;
}
function CustomerDetail({ customer, tier, dashboard, canOrders, canPricing }: { customer: AdminDashboard['customers'][number]; tier: AdminDashboard['customerTiers'][number] | undefined; dashboard: AdminDashboard; canOrders: boolean; canPricing: boolean }) {
  const [overrideState, overrideAction, overridePending] = useActionState(saveCustomerOverride, initial);
  const [adjustState, adjustAction, adjustPending] = useActionState(adjustCustomerPoints, initial);
  const [detailTab, setDetailTab] = useState<'overview' | 'orders' | 'points' | 'redemptions' | 'packages' | 'activity'>('overview');
  const customerLedger = dashboard.pointTransactions.filter((row) => row.customer_id === customer.id);
  const customerOrders = dashboard.orders.filter((row) => row.customer_id === customer.id);
  const customerRedemptions = dashboard.redemptions.filter((row) => row.customer_id === customer.id);
  const customerAudit = dashboard.auditLogs.filter((row) => row.entity_id === customer.id);
  const next = dashboard.customerTiers.filter((item) => item.is_active && item.minimum_rolling_spend_idr > (customer.rolling_spend_idr ?? 0)).sort((a, b) => a.minimum_rolling_spend_idr - b.minimum_rolling_spend_idr)[0];
  const now = Date.now();
  const eligiblePackages = dashboard.packages.filter((item) => {
    if (item.status !== 'published' || (item.starts_at && new Date(item.starts_at).getTime() > now) || (item.ends_at && new Date(item.ends_at).getTime() <= now)) return false;
    const rules = dashboard.packageEligibility.filter((rule) => rule.package_id === item.id);
    return rules.length === 0 || rules.some((rule) => (!rule.customer_id || rule.customer_id === customer.id) && (!rule.customer_tier_id || rule.customer_tier_id === customer.customer_tier_id));
  });
  const tabs = [
    ['overview', 'Overview'],
    ['orders', 'Orders'],
    ['points', 'Loyalty points'],
    ['redemptions', 'Redemptions'],
    ['packages', 'Eligible packages'],
    ['activity', 'Activity'],
  ] as const;
  return <section className="admin-panel customer-detail-panel">
    <div className="panel-heading"><div><p className="eyebrow">Customer detail</p><h3>{customer.business_name || customer.display_name || 'Customer'}</h3><small>{customer.email || customer.whatsapp || customer.phone || customer.id}</small></div><span className="status-pill status-live">{tier?.name ?? 'Basic'}</span></div>
    <div className="customer-detail-tabs" role="tablist" aria-label="Customer detail sections">{tabs.map(([value, label]) => <button key={value} type="button" role="tab" aria-selected={detailTab === value} className={detailTab === value ? 'is-active' : ''} onClick={() => setDetailTab(value)}>{label}{value === 'orders' ? ' (' + customerOrders.length + ')' : value === 'points' ? ' (' + points(customer.available_points) + ' pts)' : value === 'redemptions' ? ' (' + customerRedemptions.length + ')' : ''}</button>)}</div>
    {detailTab === 'overview' && <><div className="customer-detail-grid"><div><strong>Tier efektif</strong><b>{tier?.name ?? 'Basic'}</b><small>{next ? money(Math.max(0, next.minimum_rolling_spend_idr - (customer.rolling_spend_idr ?? 0))) + ' lagi ke ' + next.name : 'Tier tertinggi'}</small></div><div><strong>Belanja periode</strong><b>{money(customer.rolling_spend_idr ?? 0)}</b><small>Total belanja {money(customer.lifetime_paid_amount_idr)} &middot; AOV {money(customer.average_order_value_idr ?? 0)}</small></div><div><strong>Points</strong><b>{points(customer.available_points)}</b><small>Earned {points(customer.lifetime_earned_points)} &middot; Redeemed {points(customer.lifetime_redeemed_points)} &middot; Expiring {points(customer.expiring_points ?? 0)}{customer.next_expiry_at ? ' &middot; ' + new Date(customer.next_expiry_at).toLocaleDateString('id-ID') : ''}</small></div><div><strong>Last redemption</strong><b>{customer.last_redemption_at ? new Date(customer.last_redemption_at).toLocaleDateString('id-ID') : '-'}</b><small>{customer.address || 'Alamat belum diisi'}</small></div></div>{canOrders && <form className="admin-inline-form" action={overrideAction}><input type="hidden" name="customer_id" value={customer.id} /><label>Manual tier override<select name="manual_tier_id" defaultValue={customer.customer_tier_id ?? ''}>{dashboard.customerTiers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="admin-check"><input type="checkbox" name="manual_tier_override_enabled" defaultChecked={customer.manual_tier_override_enabled} /> Aktif</label><label>Alasan<input name="manual_tier_reason" required={customer.manual_tier_override_enabled} defaultValue={customer.manual_tier_reason ?? ''} placeholder="Alasan override" /></label><label>Berlaku sampai<input name="manual_tier_expires_at" type="datetime-local" defaultValue={customer.manual_tier_expires_at ? new Date(customer.manual_tier_expires_at).toISOString().slice(0, 16) : ''} /></label><button className="button button-outline" disabled={overridePending}>Simpan tier</button><ActionMessage state={overrideState} /></form>}{canPricing && <form className="admin-inline-form" action={adjustAction}><input type="hidden" name="customer_id" value={customer.id} /><label>Adjustment points<input name="points" type="number" placeholder="+100 / -50" /></label><label>Alasan<input name="reason" required placeholder="Kompensasi order" /></label><label>Referensi<input name="reference" placeholder="Order / tiket" /></label><button className="button button-dark" disabled={adjustPending}>Catat adjustment</button><ActionMessage state={adjustState} /></form>}</>}
    {detailTab === 'orders' && <div className="customer-detail-table-wrap">{customerOrders.length ? <div className="admin-data-table customer-detail-table"><div className="admin-data-head"><span>Order</span><span>Status</span><span>Pembayaran</span><span>Total</span><span>Tanggal</span></div>{customerOrders.map((row) => <div className="admin-data-row" key={row.id}><span><strong>{row.id}</strong><small>{row.contact_phone || '-'}</small></span><span>{row.status}</span><span>{row.payment_status}</span><span>{money(row.total_idr)}</span><span>{new Date(row.created_at).toLocaleDateString('id-ID')}</span></div>)}</div> : <p className="admin-empty-copy">Customer belum memiliki order.</p>}</div>}
    {detailTab === 'points' && <div className="customer-detail-table-wrap">{customerLedger.length ? <div className="admin-data-table customer-detail-table"><div className="admin-data-head"><span>Tanggal</span><span>Type</span><span>Reference</span><span>Points</span><span>Balance</span></div>{customerLedger.map((row) => <div className="admin-data-row" key={row.id}><span>{new Date(row.created_at).toLocaleDateString('id-ID')}</span><span>{row.entry_type}</span><span><strong>{row.order_id || row.redemption_id || '-'}</strong><small>{row.description}</small></span><span className={row.points_delta >= 0 ? 'action-success' : 'action-error'}>{row.points_delta >= 0 ? '+' : ''}{points(row.points_delta)} pts</span><span>{row.balance_after ?? '-'}</span></div>)}</div> : <p className="admin-empty-copy">Belum ada transaksi points.</p>}</div>}
    {detailTab === 'redemptions' && <div className="customer-detail-table-wrap">{customerRedemptions.length ? <div className="admin-data-table customer-detail-table"><div className="admin-data-head"><span>Tanggal</span><span>Reward SKU</span><span>Qty</span><span>Points</span><span>Status</span></div>{customerRedemptions.map((row) => <div className="admin-data-row" key={row.id}><span>{new Date(row.created_at).toLocaleDateString('id-ID')}</span><span>{row.sku_id || '-'}</span><span>{row.quantity}</span><span>{points(row.points_total ?? row.points_redeemed)} pts</span><span>{row.status}</span></div>)}</div> : <p className="admin-empty-copy">Belum ada redemption.</p>}</div>}
    {detailTab === 'packages' && <div className="customer-detail-table-wrap">{eligiblePackages.length ? <div className="admin-data-table customer-detail-table"><div className="admin-data-head"><span>Package</span><span>Mode</span><span>Kapasitas</span><span>Status</span><span>Catatan</span></div>{eligiblePackages.map((row) => <div className="admin-data-row" key={row.id}><span><strong>{row.title}</strong><small>{row.slug}</small></span><span>{row.selection_mode === 'free_pick' ? 'Free pick' : 'Fixed'}</span><span>{row.selection_capacity ?? '-'}</span><span>Eligible</span><span>Quantity dan minimum order dicek saat checkout.</span></div>)}</div> : <p className="admin-empty-copy">Tidak ada package eligible untuk customer ini.</p>}</div>}
    {detailTab === 'activity' && <div className="customer-detail-table-wrap">{customerAudit.length ? <div className="admin-data-table customer-detail-table"><div className="admin-data-head"><span>Tanggal</span><span>Action</span><span>Entity</span><span>Actor</span><span>Change</span></div>{customerAudit.map((row) => <div className="admin-data-row" key={row.id}><span>{new Date(row.created_at).toLocaleDateString('id-ID')}</span><span>{row.action}</span><span>{row.entity_type}</span><span>{row.actor_id || 'System'}</span><span>{row.new_value ? 'Updated' : 'Created'}</span></div>)}</div> : <p className="admin-empty-copy">Belum ada activity untuk customer ini.</p>}</div>}
  </section>;
}
function Tiers({ dashboard, canEdit }: { dashboard: AdminDashboard; canEdit: boolean }) {
  const [state, action, pending] = useActionState(saveCustomerTier, initial);
  const [query, setQuery] = useState('');
  const debounced = useDebounced(query);
  const [status, setStatus] = useState('all');
  const [sort, setSort] = useState('minimum');
  const [page, setPage] = useState(0);
  const rows = useMemo(() => dashboard.customerTiers.filter((tier) => `${tier.code} ${tier.name} ${tier.description ?? ''}`.toLowerCase().includes(debounced) && (status === 'all' || (status === 'active' ? tier.is_active : !tier.is_active))).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name) : sort === 'priority' ? b.priority - a.priority : sort === 'customers' ? dashboard.customers.filter((customer) => customer.customer_tier_id === b.id).length - dashboard.customers.filter((customer) => customer.customer_tier_id === a.id).length : a.minimum_rolling_spend_idr - b.minimum_rolling_spend_idr), [dashboard.customerTiers, dashboard.customers, debounced, status, sort]);
  return <><section className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">Customer tiers</p><h3>Atur tier dan earning points</h3></div><span className="notification-count">Basic / Premium / VIP</span></div><p className="loyalty-tier-explainer">Earning points dihitung dari transaksi paid: <strong>floor(subtotal eligible / Rp10.000 x rate tier)</strong>. Rate di bawah adalah satu-satunya pengaturan earning per transaksi; minimum spend hanya menentukan kapan tier aktif.</p><form className="admin-crud-form" action={action}><label>Code<input name="code" required placeholder="PREMIUM" disabled={!canEdit} /></label><label>Nama tier<input name="name" required placeholder="Premium" disabled={!canEdit} /></label><label>Minimum spend periode (IDR)<input name="minimum_rolling_spend_idr" type="number" min="0" required placeholder="2000000" disabled={!canEdit} /></label><label>Periode evaluasi (bulan)<input name="rolling_period_months" type="number" min="1" defaultValue="6" disabled={!canEdit} /></label><label>Points per Rp10.000<input name="points_per_10000_idr" type="number" min="0.01" step="0.01" defaultValue="1.25" disabled={!canEdit} /><small className="field-help">Contoh: 1.25 berarti belanja Rp100.000 menghasilkan 12 points.</small></label><label>Prioritas<input name="priority" type="number" min="0" step="1" defaultValue="20" disabled={!canEdit} /></label><label>Deskripsi<input name="description" placeholder="Syarat tier" disabled={!canEdit} /></label><label>Benefit<input name="benefits_description" placeholder="Contoh: earning points lebih tinggi" disabled={!canEdit} /></label><label className="admin-check"><input name="is_active" type="checkbox" defaultChecked disabled={!canEdit} /> Aktif</label><div className="admin-crud-action"><ActionMessage state={state} /><button className="button button-dark" disabled={!canEdit || pending}>{pending ? 'Menyimpan...' : 'Tambah tier'}</button></div></form></section>
    <section className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">Saved tiers</p><h3>Tier customer</h3></div><span className="notification-count">{rows.length} tier</span></div><div className="admin-table-controls"><label className="admin-table-search-label">Search<input className="admin-table-search" value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} placeholder="Code, nama, atau deskripsi" /></label><label>Status<select value={status} onChange={(event) => { setStatus(event.target.value); setPage(0); }}><option value="all">Semua status</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select></label><label>Urutkan<select value={sort} onChange={(event) => { setSort(event.target.value); setPage(0); }}><option value="minimum">Minimum spend</option><option value="priority">Prioritas</option><option value="customers">Jumlah customer</option><option value="name">Nama A-Z</option></select></label></div><div className="admin-data-table tier-table"><div className="admin-data-head"><span>Tier</span><span>Mulai dari</span><span>Periode</span><span>Earning rate</span><span>Customer</span><span>Status</span><span>Aksi</span></div>{rows.slice(page * 10, page * 10 + 10).map((tier) => <TierRow key={tier.id} tier={tier} customerCount={dashboard.customers.filter((customer) => customer.customer_tier_id === tier.id).length} canEdit={canEdit} />)}</div>{!rows.length && <p className="admin-empty-copy">Belum ada tier yang cocok.</p>}<Pager page={page} total={rows.length} onPage={setPage} /></section></>;
}

function TierRow({ tier, customerCount, canEdit }: { tier: AdminDashboard['customerTiers'][number]; customerCount: number; canEdit: boolean }) {
  const [state, action, pending] = useActionState(saveCustomerTier, initial);
  const [archiveState, archiveAction, archivePending] = useActionState(archiveCustomerTier, initial);
  const [editing, setEditing] = useState(false);
  return <div className="tier-editor-record"><div className="admin-data-row tier-summary-row"><span><strong>{tier.name}</strong><small>{tier.code} / prioritas {tier.priority}</small></span><span>{money(tier.minimum_rolling_spend_idr)}</span><span>{tier.rolling_period_months} bulan</span><span>{tier.points_per_10000_idr} pts / Rp10rb</span><span>{customerCount}</span><span>{tier.is_active ? 'Aktif' : 'Nonaktif'}</span><span><button className="button button-outline" type="button" onClick={() => setEditing((value) => !value)}>{editing ? 'Tutup' : 'Edit'}</button></span></div>{editing && <div className="tier-editor-detail"><form className="admin-crud-form admin-tier-editor-form" action={action}><input type="hidden" name="id" value={tier.id} /><label>Code<input name="code" defaultValue={tier.code} disabled={!canEdit} /></label><label>Nama tier<input name="name" defaultValue={tier.name} disabled={!canEdit} /></label><label>Minimum spend periode (IDR)<input name="minimum_rolling_spend_idr" type="number" min="0" defaultValue={tier.minimum_rolling_spend_idr} disabled={!canEdit} /></label><label>Periode evaluasi (bulan)<input name="rolling_period_months" type="number" min="1" defaultValue={tier.rolling_period_months} disabled={!canEdit} /></label><label>Points per Rp10.000<input name="points_per_10000_idr" type="number" min="0.01" step="0.01" defaultValue={tier.points_per_10000_idr} disabled={!canEdit} /></label><label>Prioritas<input name="priority" type="number" min="0" defaultValue={tier.priority} disabled={!canEdit} /></label><label>Deskripsi<input name="description" defaultValue={tier.description ?? ''} disabled={!canEdit} /></label><label>Benefit<input name="benefits_description" defaultValue={tier.benefits_description ?? ''} disabled={!canEdit} /></label><label className="admin-check"><input name="is_active" type="checkbox" defaultChecked={tier.is_active} disabled={!canEdit} /> Aktif</label><div className="admin-crud-record-foot"><ActionMessage state={state} /><button className="button button-outline" disabled={!canEdit || pending}>{pending ? 'Menyimpan...' : 'Simpan tier'}</button></div></form><form action={archiveAction} onSubmit={(event) => { if (!window.confirm('Arsipkan tier ' + tier.name + '?')) event.preventDefault(); }}><input type="hidden" name="id" value={tier.id} /><button className="text-button danger-button" disabled={!canEdit || archivePending}>{archivePending ? '...' : 'Arsipkan'}</button>{archiveState.message && <small className={archiveState.ok ? 'action-success' : 'action-error'}>{archiveState.message}</small>}</form></div>}</div>;
}function Rewards({ dashboard, canEdit }: { dashboard: AdminDashboard; canEdit: boolean }) { const [state, action, pending] = useActionState(saveReward, initial); return <><section className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">Free product catalog</p><h3>Tambah reward</h3></div><span className="notification-count">Reward bukan diskon checkout</span></div><form className="admin-crud-form" action={action}><label>SKU reward<select name="sku_id" required>{dashboard.skus.map((sku) => <option key={sku.id} value={sku.id}>{sku.sku}  /  {sku.name}</option>)}</select></label><label>Nama reward<input name="reward_name" placeholder="Free Base Coat" /></label><label>Point cost<input name="points_cost" type="number" min="1" required /></label><label>HPP<input name="hpp_idr" type="number" min="0" /></label><label>Harga retail<input name="normal_selling_price_idr" type="number" min="0" /></label><label>Minimum tier<select name="minimum_customer_tier_id"><option value="">Semua tier</option>{dashboard.customerTiers.map((tier) => <option key={tier.id} value={tier.id}>{tier.name}</option>)}</select></label><label>Minimum order<input name="minimum_order_value_idr" type="number" min="0" /></label><label>Max qty / redemption<input name="max_redemption_quantity" type="number" min="1" defaultValue="1" /></label><label>Stock (0 = unlimited)<input name="reward_stock" type="number" min="0" defaultValue="0" /></label><label className="admin-check"><input name="is_active" type="checkbox" defaultChecked /> Aktif</label><div className="admin-crud-action"><ActionMessage state={state} /><button className="button button-dark" disabled={!canEdit || pending}>Simpan reward</button></div></form></section><section className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">Reward catalog</p><h3>Reward tersimpan</h3></div><span className="notification-count">{dashboard.rewards.length} reward</span></div>{dashboard.rewards.map((reward) => <RewardRow key={reward.id} reward={reward} dashboard={dashboard} canEdit={canEdit} />)}</section></>; }

function RewardRow({ reward, dashboard, canEdit }: { reward: AdminDashboard['rewards'][number]; dashboard: AdminDashboard; canEdit: boolean }) { const [state, action, pending] = useActionState(saveReward, initial); const [archiveState, archiveAction, archivePending] = useActionState(archiveReward, initial); const [deleteState, deleteAction, deletePending] = useActionState(deleteReward, initial); return <div className="admin-data-row admin-data-row-form"><form action={action}><input type="hidden" name="id" value={reward.id} /><select name="sku_id" defaultValue={reward.sku_id} disabled={!canEdit}>{dashboard.skus.map((sku) => <option key={sku.id} value={sku.id}>{sku.sku}</option>)}</select><input name="reward_name" defaultValue={reward.reward_name ?? ''} disabled={!canEdit} /><input name="points_cost" type="number" min="1" defaultValue={reward.points_cost} disabled={!canEdit} /><input name="hpp_idr" type="number" min="0" defaultValue={reward.hpp_idr} disabled={!canEdit} /><input name="normal_selling_price_idr" type="number" min="0" defaultValue={reward.normal_selling_price_idr} disabled={!canEdit} /><input name="minimum_order_value_idr" type="number" min="0" defaultValue={reward.minimum_order_value_idr} disabled={!canEdit} /><input name="max_redemption_quantity" type="number" min="1" defaultValue={reward.max_redemption_quantity} disabled={!canEdit} /><input name="reward_stock" type="number" min="0" defaultValue={reward.reward_stock} disabled={!canEdit} /><select name="minimum_customer_tier_id" defaultValue={reward.minimum_customer_tier_id ?? ''} disabled={!canEdit}><option value="">Semua tier</option>{dashboard.customerTiers.map((tier) => <option key={tier.id} value={tier.id}>{tier.name}</option>)}</select><input type="hidden" name="is_active" value={reward.is_active ? 'on' : ''} /><button className="button button-outline" disabled={!canEdit || pending}>Simpan</button>{state.message && <small>{state.message}</small>}</form><form action={archiveAction}><input type="hidden" name="id" value={reward.id} /><button className="text-button" disabled={!canEdit || archivePending}>Arsipkan</button>{archiveState.message && <small>{archiveState.message}</small>}</form><form action={deleteAction}><input type="hidden" name="id" value={reward.id} /><input type="hidden" name="sku_id" value={reward.sku_id} /><button className="text-button danger-button" disabled={!canEdit || deletePending}>Hapus</button>{deleteState.message && <small>{deleteState.message}</small>}</form></div>; }

function Redemptions({ dashboard, canEdit }: { dashboard: AdminDashboard; canEdit: boolean }) {
  const [query, setQuery] = useState('');
  const debounced = useDebounced(query);
  const [status, setStatus] = useState('all');
  const [sort, setSort] = useState('newest');
  const [page, setPage] = useState(0);
  const customerNames = useMemo(() => new Map(dashboard.customers.map((customer) => [customer.id, customer.business_name || customer.display_name || customer.email || customer.id])), [dashboard.customers]);
  const rows = useMemo(() => dashboard.redemptions.filter((row) => {
    const customerName = customerNames.get(row.customer_id) || '';
    const rewardName = dashboard.rewards.find((reward) => reward.sku_id === row.sku_id)?.reward_name || row.sku_id || '';
    return `${customerName} ${row.customer_id} ${row.order_id} ${rewardName} ${row.sku_id ?? ''} ${row.status}`.toLowerCase().includes(debounced)
      && (status === 'all' || row.status === status);
  }).sort((a, b) => sort === 'points'
    ? Number(b.points_total ?? b.points_redeemed) - Number(a.points_total ?? a.points_redeemed)
    : sort === 'quantity' ? b.quantity - a.quantity
    : sort === 'oldest' ? a.created_at.localeCompare(b.created_at)
    : b.created_at.localeCompare(a.created_at)), [dashboard.redemptions, dashboard.customers, dashboard.rewards, customerNames, debounced, status, sort]);
  return <section className={'admin-panel'}><div className={'panel-heading'}><div><p className={'eyebrow'}>Reward fulfillment</p><h3>Redemptions</h3></div><span className={'notification-count'}>{rows.length} of {dashboard.redemptions.length} redemption</span></div>
    <div className={'admin-table-controls'}><label className="admin-table-search-label">Search<input className={'admin-table-search'} value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} placeholder={'Customer, reward, order, SKU, atau status'} /></label><label>Status<select value={status} onChange={(event) => { setStatus(event.target.value); setPage(0); }}><option value={'all'}>Semua status</option><option value={'pending'}>Pending</option><option value={'applied'}>Applied</option><option value={'confirmed'}>Confirmed</option><option value={'fulfilled'}>Fulfilled</option><option value={'cancelled'}>Cancelled</option><option value={'reversed'}>Reversed</option></select></label><label>Urutkan<select value={sort} onChange={(event) => { setSort(event.target.value); setPage(0); }}><option value={'newest'}>Terbaru</option><option value={'oldest'}>Terlama</option><option value={'points'}>Points terbesar</option><option value={'quantity'}>Qty terbesar</option></select></label></div>
    <div className="admin-data-table redemption-table"><div className="admin-data-head"><span>Tanggal</span><span>Customer</span><span>Reward / SKU</span><span>Qty</span><span>Points used</span><span>Order</span><span>Tier</span><span>Status</span><span>Aksi</span></div>
      {rows.slice(page * 10, page * 10 + 10).map((redemption) => <RedemptionRow key={redemption.id} redemption={redemption} canEdit={canEdit} customerName={customerNames.get(redemption.customer_id) || redemption.customer_id} rewardName={dashboard.rewards.find((reward) => reward.sku_id === redemption.sku_id)?.reward_name || redemption.sku_id || '-'} tierName={dashboard.customerTiers.find((tier) => tier.id === dashboard.customers.find((customer) => customer.id === redemption.customer_id)?.customer_tier_id)?.name || 'Basic'} />)}
    </div>
    {!rows.length && <p className={'admin-empty-copy'}>Belum ada redemption yang cocok.</p>}<Pager page={page} total={rows.length} onPage={setPage} />
  </section>;
}

function RedemptionRow({ redemption, canEdit, customerName, rewardName, tierName }: { redemption: AdminDashboard['redemptions'][number]; canEdit: boolean; customerName: string; rewardName: string; tierName: string }) {
  const [state, action, pending] = useActionState(updateRedemptionStatus, initial);
  return <form className="admin-data-row" action={action} onSubmit={(event) => { const nextStatus = new FormData(event.currentTarget).get('status'); if ((nextStatus === 'cancelled' || nextStatus === 'reversed') && !window.confirm('Batalkan atau reverse redemption ini? Points dan stok akan disesuaikan oleh sistem.')) event.preventDefault(); }}>
    <input type="hidden" name="id" value={redemption.id} />
    <span>{new Date(redemption.created_at).toLocaleDateString('id-ID')}</span>
    <span><strong>{customerName}</strong><small>{redemption.customer_id}</small></span>
    <span><strong>{rewardName}</strong><small>{redemption.sku_id || '-'}</small></span>
    <span>{redemption.quantity}</span>
    <span>{points(redemption.points_total ?? redemption.points_redeemed)} pts</span>
    <span>{redemption.order_id}</span>
    <span>{tierName}</span>
    <span><select name="status" defaultValue={redemption.status} disabled={!canEdit}><option value="pending">Pending</option><option value="applied">Applied</option><option value="confirmed">Confirmed</option><option value="fulfilled">Fulfilled</option><option value="cancelled">Cancelled</option><option value="reversed">Reversed</option></select></span>
    <span><button className="button button-outline" disabled={!canEdit || pending}>{pending ? 'Menyimpan' : 'Simpan'}</button>{state.message && <small className={state.ok ? 'action-success' : 'action-error'}>{state.message}</small>}</span>
  </form>;
}
function Settings({ dashboard, canEdit }: { dashboard: AdminDashboard; canEdit: boolean }) { const [state, action, pending] = useActionState(saveLoyaltySettings, initial); const settings = dashboard.loyaltySettings; return <section className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">Program configuration</p><h3>Aturan Luminails Points</h3></div><span className="notification-count">{canEdit ? 'Owner editable' : 'Read only'}</span></div><p className="loyalty-settings-explainer">Belanja eligible ini menjadi dasar rekomendasi reward point. Earning transaksi diatur oleh rate masing-masing tier. Saran point = ceil((HPP × multiplier tier tertinggi × 100) ÷ (nilai 1 point dalam rupiah × warning cost %)). Harga final tetap bisa Anda adjust di reward catalog.</p><form className="admin-crud-form" action={action}><label>Belanja eligible untuk 1 point<input name="point_unit_value_idr" type="number" min="1" defaultValue={settings?.point_unit_value_idr ?? 10000} disabled={!canEdit} /></label><label>Expiry bulan<input name="expiry_months" type="number" min="1" defaultValue={settings?.expiry_months ?? 12} disabled={!canEdit} /></label><label>Warning reward cost %<input name="reward_cost_warning_percent" type="number" min="0" step="0.01" defaultValue={settings?.reward_cost_warning_percent ?? 3} disabled={!canEdit} /></label><label>Rolling tier bulan<input name="tier_rolling_period_months" type="number" min="1" defaultValue={settings?.tier_rolling_period_months ?? 6} disabled={!canEdit} /></label><label className="admin-check"><input name="automatic_tier_recalculation" type="checkbox" defaultChecked={settings?.automatic_tier_recalculation ?? true} disabled={!canEdit} /> Recalculate otomatis</label><label className="admin-check"><input name="allow_manual_point_adjustment" type="checkbox" defaultChecked={settings?.allow_manual_point_adjustment ?? true} disabled={!canEdit} /> Allow adjustment</label><label className="admin-check"><input name="require_adjustment_reason" type="checkbox" defaultChecked={settings?.require_adjustment_reason ?? true} disabled={!canEdit} /> Wajib alasan</label><div className="admin-crud-action"><ActionMessage state={state} /><button className="button button-dark" disabled={!canEdit || pending}>Simpan settings</button></div></form></section>; }

function Ledger({ dashboard }: { dashboard: AdminDashboard }) {
  const [query, setQuery] = useState('');
  const debounced = useDebounced(query);
  const [entryType, setEntryType] = useState('all');
  const [customerId, setCustomerId] = useState('all');
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');
  const [sort, setSort] = useState('newest');
  const [page, setPage] = useState(0);
  const customerNames = useMemo(() => new Map(dashboard.customers.map((customer) => [customer.id, customer.business_name || customer.display_name || customer.email || customer.id])), [dashboard.customers]);
  const rows = useMemo(() => dashboard.pointTransactions.filter((row) => {
    const customerName = customerNames.get(row.customer_id) || '';
    const haystack = [customerName, row.customer_id, row.order_id, row.redemption_id, row.entry_type, row.description, row.reference_text].filter(Boolean).join(' ').toLowerCase();
    const rowDate = new Date(row.created_at).getTime();
    const from = dateFrom ? new Date(dateFrom + 'T00:00:00').getTime() : -Infinity;
    const to = dateTo ? new Date(dateTo + 'T23:59:59').getTime() : Infinity;
    const typeMatch = entryType === 'all' || (entryType === 'adjustment' ? row.entry_type.startsWith('adjustment') : row.entry_type === entryType);
    return haystack.includes(debounced) && typeMatch && (customerId === 'all' || row.customer_id === customerId) && rowDate >= from && rowDate <= to;
  }).sort((a, b) => sort === 'oldest' ? a.created_at.localeCompare(b.created_at) : sort === 'points' ? Math.abs(b.points_delta) - Math.abs(a.points_delta) : sort === 'expiry' ? (a.expires_at || '9999').localeCompare(b.expires_at || '9999') : b.created_at.localeCompare(a.created_at)), [dashboard.pointTransactions, customerNames, debounced, entryType, customerId, dateFrom, dateTo, sort]);
  return <section className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">Immutable audit trail</p><h3>Point ledger</h3></div><span className="notification-count">{rows.length} of {dashboard.pointTransactions.length} entries</span></div><div className="admin-table-controls ledger-controls"><label className="admin-table-search-label">Search<input className="admin-table-search" value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} placeholder="Customer, order, reference, atau deskripsi" /></label><label>Type<select value={entryType} onChange={(event) => { setEntryType(event.target.value); setPage(0); }}><option value="all">Semua type</option><option value="earn">Earn</option><option value="redeem">Redeem</option><option value="reversal">Reversal</option><option value="expired">Expired</option><option value="adjustment">Adjustment</option></select></label><label>Customer<select value={customerId} onChange={(event) => { setCustomerId(event.target.value); setPage(0); }}><option value="all">Semua customer</option>{dashboard.customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.business_name || customer.display_name || customer.id}</option>)}</select></label><label>Dari<input type="date" value={dateFrom} onChange={(event) => { setDateFrom(event.target.value); setPage(0); }} /></label><label>Sampai<input type="date" value={dateTo} onChange={(event) => { setDateTo(event.target.value); setPage(0); }} /></label><label>Urutkan<select value={sort} onChange={(event) => { setSort(event.target.value); setPage(0); }}><option value="newest">Terbaru</option><option value="oldest">Terlama</option><option value="points">Point terbesar</option><option value="expiry">Expiry terdekat</option></select></label></div><div className="admin-data-table ledger-table"><div className="admin-data-head"><span>Date</span><span>Customer</span><span>Type</span><span>Reference</span><span>Points</span><span>Balance after</span><span>Expiry</span><span>Created by</span></div>{rows.slice(page * 10, page * 10 + 10).map((row) => <div className="admin-data-row" key={row.id}><span>{new Date(row.created_at).toLocaleDateString('id-ID')}</span><span>{customerNames.get(row.customer_id) || row.customer_id}</span><span>{row.entry_type}</span><span><strong>{row.order_id || row.redemption_id || row.reference_text || '-'}</strong><small>{row.description}</small></span><span className={row.points_delta >= 0 ? 'action-success' : 'action-error'}>{row.points_delta >= 0 ? '+' : ''}{points(row.points_delta)} pts</span><span>{row.balance_after ?? '-'}</span><span>{row.expires_at ? new Date(row.expires_at).toLocaleDateString('id-ID') : '-'}</span><span>{row.created_by || 'System'}</span></div>)}</div>{!rows.length && <p className="admin-empty-copy">Tidak ada transaksi points yang cocok.</p>}<Pager page={page} total={rows.length} onPage={setPage} /></section>;
}
